parameters:

services:

    qb.repository.oauth_info:
        class: Quickbooks\Repository\OAuthInfoRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - QuickbooksBundle\Entity\OAuthInfo

    qb.entity_manager:
        class: QuickbooksBundle\Service\QuickbooksEntityService
        arguments:
            - "@qb.repository.oauth_info"
            - %quickbooks.base_url%
            - %quickbooks.export_dir%
            - %quickbooks.oauth.consumer_key%
            - %quickbooks.oauth.consumer_secret%